from __future__ import annotations

import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))
if str(ROOT / "src") not in sys.path:
    sys.path.insert(0, str(ROOT / "src"))

try:
    import tests.conftest  # noqa: F401
except ModuleNotFoundError:
    pass
from tests.parity._api import MODULES, case_report, collect_cases


def main() -> int:
    lines = [
        "# MicroPython API Parity",
        "",
        "Generated by `python tests/parity/report.py` from the installed `micropython-rp2-stubs` package.",
        "",
    ]
    total = 0
    failing = 0
    for module in MODULES:
        lines.append(f"## `{module}`")
        lines.append("")
        lines.append("| Symbol | Status | Detail |")
        lines.append("|--------|--------|--------|")
        cases = collect_cases(module)
        for case in cases:
            symbol, status, detail = case_report(case)
            total += 1
            if status not in {"provided", "allowlisted"}:
                failing += 1
            lines.append(f"| `{symbol}` | {status} | {escape(detail)} |")
        lines.append("")
    lines.append(f"Total symbols: {total}")
    lines.append(f"Unexpected failures: {failing}")
    lines.append("")
    (ROOT / "docs" / "parity.md").write_text("\n".join(lines), encoding="utf-8")
    return 0


def escape(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ")


if __name__ == "__main__":
    raise SystemExit(main())
